import * as express from "express";
import * as bodyParser from "body-parser";
import * as methodOverride from "method-override";
import * as morgan from "morgan";
import * as compression from "compression";
import * as helmet from "helmet";
import * as cors from "cors";
import * as path from "path";
import * as routes from "../app/routes";
import * as logger from "./logger";
import { logs } from "./vars";
import * as error from "../app/middleware/error";

const app = express();
app.use(morgan(logs, { stream: logger.stream }));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(methodOverride());
app.use(cors());
app.use(helmet());
app.use(compression());
app.use(express.static("views"));
app.set("../views", path.join(__dirname, "views"));
app.set("view engine", "pug");
app.use(routes);
app.use(error.converter);
app.use(error.notFound);
app.use(error.handler);

module.exports = app;
